# -*- coding: utf-8 -*-
"""Task0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-p2_fp9oNVr5BJrGqG2Kp7hhCjsAXw5l
"""

for num in range(1,101):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz: "+str(num))
    elif num % 3 == 0:
        print("Fizz:" +str(num))
    elif num % 5 == 0:
        print("Buzz:" +str(num))
    else:
        print(num)